---
Name: elementalbannerblockconfig
---
SilverStripe\Core\Injector\Injector:
  Link:
    class: SilverStripe\ElementalBannerBlock\ORM\FieldType\DBLink

DNADesign\Elemental\Controllers\ElementController:
  default_styles:
    - silverstripe/elemental-bannerblock:client/dist/styles/frontend-default.css

#SilverStripe\Admin\LeftAndMain:
#  extra_requirements_javascript:
#    - 'silverstripe/elemental-bannerblock:client/dist/js/bundle.js'
